Importar la librería, asignar las variables y crear la conección

In [ ]:
import pyodbc

server = 'localhost\\SQLEXPRESS'
database = 'master'

# Create a connection string
conn_str = (
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=' + server + ';'  # replace with your server name
    'DATABASE=' + database + ';'  # the database you want to connect to
    'Trusted_Connection=yes;'
)

Crear la base de datos

In [ ]:
# Create a connection
conn = pyodbc.connect(conn_str, autocommit=True) # El autocommint en True permite crear la base desde el codigo

# Create a cursor
cursor = conn.cursor()

# Execute the CREATE DATABASE statement
cursor.execute('CREATE DATABASE DAFT01_Grupo1_nba')  # replace with your database name

# Close the cursor and the connection
cursor.close()
conn.close()

Creacion de las tablas y sus relaciones

In [ ]:
database = 'DAFT01_Grupo1_nba' # Cambiar a la base de datos que ocupemos

# Create a connection string
conn_str = (
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=' + server + ';'  # replace with your server name
    'DATABASE=' + database + ';'  # the database you want to connect to
    'Trusted_Connection=yes;'
)

# Create a connection
conn = pyodbc.connect(conn_str, autocommit=True)

# Crear un cursor
cursor = conn.cursor()

# Crear Proveniencia PREGUNTAR QUE TIPO DE DATO ES TYPE
cursor.execute('''
CREATE TABLE Proveniencia (
    ID_proveniencia INT PRIMARY KEY,
    organization_type NVARCHAR(100),
    organization NVARCHAR(100),
)
''')


# Crear State
cursor.execute('''
CREATE TABLE State (
    ID_state INT PRIMARY KEY,
    state NVARCHAR(100),
)
''')

# Crear City
cursor.execute('''
CREATE TABLE City (
    ID_city INT PRIMARY KEY,
    city NVARCHAR(100),
)
''')

# Crear Location
cursor.execute('''
CREATE TABLE Location (
    ID_location INT PRIMARY KEY,
    ID_city NVARCHAR(100),
    ID_state NVARCHAR(100)
)
''')


# Crear Player
cursor.execute('''
CREATE TABLE Player (
    ID_player INT PRIMARY KEY,
    first_name NVARCHAR(100),
    last_name NVARCHAR(100),
    birthdate DATE,
    height NVARCHAR(100),
    weight INT,
    season_exp FLOAT,
    jersey INT,
    position NVARCHAR(100),
    ID_team INT,
    is_active INT,
)
''')

# Crear Teams  PREGUNTAR POR ID TEAMS QUE ESTABA SOLO ID (year active till?)
cursor.execute('''
CREATE TABLE teams (
    ID_team INT PRIMARY KEY,
    full_name NVARCHAR(100),
    abbreviation NVARCHAR(100),
    owner NVARCHAR(100),
    generalmanager NVARCHAR(100),
    headcoach NVARCHAR(100),
    year_founded INT,
    year_active_till INT,
    ID_location INT,
    ID_arena INT,
    estado INT,
)
''')

# Crear Arena
cursor.execute('''
CREATE TABLE Arena (
    ID_arena INT PRIMARY KEY,
    arena NVARCHAR(100),
    arenacapacity INT,
)
''')

# Crear Games
cursor.execute('''
CREATE TABLE Games (
    ID_game INT PRIMARY KEY,
    game_date DATE,
    ID_team INT,
    wl_home NVARCHAR(100),
    team_id_away INT,
    wl_away NVARCHAR(100),
    ID_season,
    ID_location,
)
''')

# Crear season
cursor.execute('''
CREATE TABLE season (
    ID_season INT PRIMARY KEY,
    season_type NVARCHAR(100),
    season INT,
)
''')

# Crear Draft   CUAL ES SU PRIMARY KEY? TIENE ID?
cursor.execute('''
CREATE TABLE Draft (
    ID_player INT,
    weight INT,
    wingspan FLOAT,
    standing_reach FLOAT,
    body_fat_pct FLOAT,
    standing_vertical_leap FLOAT,
    max_vertical_leap FLOAT,
    lane_agility_time TIME,
    modified_lane_agility_time TIME,
    three_quarter_sprint TIME,
    bench_press TIME,     
    round_number INT,
    round_pick INT,
    overall_pick INT,
    ID_team INT,
    ID_proveniencia INT, 
    ID_season INT,     
)
''')

# Crear Game_stats
cursor.execute('''
CREATE TABLE Game_stats (
    ID_game INT,
    pts_home_x INT,
    pts_qtr1_home INT,
    pts_qtr2_home INT,
    pts_qtr3_home INT,
    pts_qtr4_home INT,
    pts_qtr1_away INT,
    pts_qtr2_away INT,
    pts_qtr3_away INT,
    pts_qtr4_away INT,
    pts_away_x INT,
    attendance INT,
    game_time TIME,
    natl_tv_broadcaster_abbreviation NVARCHAR(100),
    live_period_time_bcast NVARCHAR(100),           
)
''')

# Confirmar los cambios
conn.commit()

# Cerrar la conexión
cursor.close()
conn.close()

Creacion de las relaciones

In [ ]:
#-------------------------------------- GENERAR RELACIONES --------------------------------------#
database = 'DAFT01_Grupo1_nba' # Cambiar a la base de datos que ocupemos

# Create a connection string
conn_str = (
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=' + server + ';'  # replace with your server name
    'DATABASE=' + database + ';'  # the database you want to connect to
    'Trusted_Connection=yes;'
)

# Create a connection
conn = pyodbc.connect(conn_str, autocommit=True)

# Crear un cursor
cursor = conn.cursor()


cursor.execute('''
ALTER TABLE player_stats
ADD CONSTRAINT FK_Player_Stats
FOREIGN KEY(ID_player) REFERENCES Player(ID_player);
''')

cursor.execute('''
ALTER TABLE player_stats
ADD CONSTRAINT FK_player_Proveniencia
FOREIGN KEY(ID_proveniencia) REFERENCES Proveniencia(ID_proveniencia);
''')

cursor.execute('''
ALTER TABLE Location
ADD CONSTRAINT FK_Location_Country
FOREIGN KEY(ID_country) REFERENCES Country(ID_country);
''')

cursor.execute('''
ALTER TABLE Location
ADD CONSTRAINT FK_Location_State
FOREIGN KEY(ID_state) REFERENCES State(ID_state);
''')

cursor.execute('''
ALTER TABLE City
ADD CONSTRAINT FK_Location_City
FOREIGN KEY(ID_city) REFERENCES City(ID_city);
''')

cursor.execute('''
ALTER TABLE Teams
ADD CONSTRAINT FK_Teams_Location
FOREIGN KEY(ID_location) REFERENCES Location(ID_location);
''')

cursor.execute('''
ALTER TABLE Teams
ADD CONSTRAINT FK_Teams_Arena
FOREIGN KEY(ID_arena) REFERENCES Arena(ID_arena);
''')

cursor.execute('''
ALTER TABLE Games
ADD CONSTRAINT FK_Games_Location
FOREIGN KEY(ID_location) REFERENCES Location(ID_location);
''')

cursor.execute('''
ALTER TABLE Games
ADD CONSTRAINT FK_Games_Dates
FOREIGN KEY(ID_date) REFERENCES Dates(ID_date);
''')

cursor.execute('''
ALTER TABLE Games_Stats
ADD CONSTRAINT FK_Games_Stats
FOREIGN KEY(ID_game) REFERENCES Games(ID_game);
''')

cursor.execute('''
ALTER TABLE Draft
ADD CONSTRAINT FK_Draft_Player
FOREIGN KEY(ID_player) REFERENCES Player(ID_player);
''')

# Confirmar los cambios
conn.commit()

# Cerrar la conexión
cursor.close()
conn.close()